name=SLT5006
version=0.1.0
author=Interested-In-Spresense
maintainer=Interested-In-Spresense
sentence=UART driver library for Murata SLT5006 soil sensor.
paragraph=Precompiled static library package for Spresense with public API header.
category=Signal Input/Output
architectures=spresense
includes=SLT5006.h
precompiled=true
